name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-ambitious-wave-0a3338810-variable-group
  steps:
  - checkout: self
    submodules: true
    
  
  - task: Docker@2
    displayName: buildAndPush
    inputs:
     containerRegistry: myconn
     repository: reactapp
     buildContext: '$(System.DefaultWorkingDirectory)'
     tags: |
      $(Build.BuildId)
      latest

  - task: CopyFiles@2
    inputs:
     SourceFolder: '$(agent.builddirectory)'
     Contents: '**/dep.yml'
     TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishPipelineArtifact@1
    inputs: 
     targetPath: '$(Build.ArtifactStagingDirectory)'
     artifactName: 'drop'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_WAVE_0A3338810)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "build" # Built app content directory - optional
###### End of Repository/Build Configurations ######
