apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactfrontend
spec:
  replicas: 2  # Set the desired number of replicas based on your needs
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: react-app-container
          image: studentregimages.azurecr.io/reactapp:196  # Replace with your Docker image URL
          ports:
            - containerPort: 3000  # The port your React app is listening on

---

apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  selector:
    app: reactapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the LoadBalancer service
      targetPort: 3000  # The port your React app is listening on inside the container
